### ISSUE TITLE
Src is always downloaded

### ISSUE THREAD

**Issue by Kcko** [ivopetkov/responsively-lazy#20]
This solution has a one unresolved behavior. 
Each browser downloads image in src before when plugin switch image in data-src.

In your example each browser download 2000px image and after then decides what to replace and show.
i think that is not very useful to insert a large picture like a fallback.

Try to mention this behavior in readme.md

**Comment by ivopetkov** [comment]
Only the browsers that do not support the `srcset` attribute load the value in the `src` attribute. That's why the `srcset="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="` part is so important. You can read more about this at [http://ivopetkov.com/b/lazy-load-responsive-images/](http://ivopetkov.com/b/lazy-load-responsive-images/)

**Comment by Kcko** [comment]
Ok thx :-)
